namespace SpaceShooterProject.State 
{
    public enum StateTriggers
    {
        NONE,
        SPLASH_LOADING,
        INTRO_SCENE,
        SPLASH_COMPLETED,
        RETURN_MAIN_MENU_FROM_ACHIEVEMENTS,
        OPEN_ACHIEVEMENT,
        OPEN_CARD,
        OPEN_SPACESHIP,
        RETURN_TO_INVENTORY,
        GO_TO_MARKET_REQUEST,
        GO_TO_MAIN_MENU_REQUEST,
        GO_TO_ACHIEVEMENTS_REQUEST,
        GO_TO_SPACE_SHIP_UPGRADE_REQUEST,
        GO_TO_GARAGE_REQUEST,
        GO_TO_SETTINGS_REQUEST,
        GO_TO_INVENTORY_REQUEST,
        GO_TO_CO_PILOT_REQUEST,
        GO_TO_QUOTE_REQUEST,
        START_GAME_REQUEST,
        PLAY_GAME_REQUEST,
        PAUSE_GAME_REQUEST,
        RESUME_GAME_REQUEST,
        GAME_OVER,
        REPLAY_GAME_REQUEST,
        GO_TO_CREDITS,
        GO_TO_QUOTE_REQUEST
    }
}


